---
# tasks file for roles/ubuntu-Nagios

#- name: Update and Upgrade apt packages
#  apt:
#    update_cache: yes
#    upgrade: 'yes'

- name: Install Prerequisite of Nagios Core
  apt:
    name:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php
      - libgd-dev
    state: latest
    update_cache: yes

- name: Download nagios-4.4.5.tar.gz
  get_url:
    url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp/nagios-4.4.5.tar.gz

- name: Unarchive nagios-4.4.5.tar.gz
  unarchive:
    src: /tmp/nagios-4.4.5.tar.gz
    dest: /tmp/
    remote_src: yes
  register: unarchive_nagios

- name: Configure Nagios Core to use Apache as the web server
  shell:
    chdir: /tmp/nagios-4.4.5
    cmd: "./configure --with-httpd-conf=/etc/apache2/sites-enabled"
  when: unarchive_nagios.changed

- name: Compile the main Nagios program and CGIs
  make:
    chdir: /tmp/nagios-4.4.5
    target: all
  when: unarchive_nagios.changed

- name: Create Nagios Core user and group
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-groups-users
  when: unarchive_nagios.changed

- name: Add the user to the Apache web server group
  user:
    name: ubuntu-nagios-rada
    comment: New user for nagios
    group: www-data
    append: yes

- name: Install Nagios Core main program, CGIs, and HTML files
  make:
    chdir: /tmp/nagios-4.4.5
    target: install
  when: unarchive_nagios.changed

- name: Install Nagios Core startup scripts
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-init
  when: unarchive_nagios.changed

- name: Initialize the init scripts
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-daemoninit
  when: unarchive_nagios.changed

- name: Install and configure permissions on the directory for holding the Nagios Core external command file
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-commandmode
  when: unarchive_nagios.changed

- name: Install Nagios Core sample configuration files in /usr/local/nagios/etc
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-config
  when: unarchive_nagios.changed

- name: Install Apache configuration file for the Nagios web interface
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-webconf
  when: unarchive_nagios.changed

- name: Enable apache2 rewrite
  apache2_module:
    state: present
    name: rewrite

- name: Enable apache2 cgi
  apache2_module:
    state: present
    name: cgi

- name: Download nagios plugins
  get_url:
    url: https://github.com/nagios-plugins/releases/download/release-2.3.3/nagios-plugins-2.3.3.tar.gz
    dest: /tmp/
  register: download_plugins

- name: Extract the nagios plugins
  unarchive:
    src: /tmp/nagios-plugins-2.3.3.tar.gz
    dest: /tmp/
    remote_src: yes
  when: download_plugins.changed

- name: Compile nagios plugins
  shell:
    chdir: /tmp/nagios-plugins-2.3.3
    cmd: "./configure"
  when: download_plugins.changed

- name: build the default nagios plugins
  make:
    chdir: /tmp/nagios-plugins-2.3.3/
  when: download_plugins.changed

- name: install in nagios plugins
  make:
    chdir: /tmp/nagios-plugins-2.3.3/
    target: install
  when: download_plugins.changed

- name: Configure Nagios Core Web Interface basic authentication
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: ubuntu-admin-rada
    password: leslieadmin
#    crypt_scheme: md5_crypt
  register: config_auth

- name: Enable and Start nagios
  systemd:
    name: nagios
    state: started
    enabled: yes

- name: Restart and Enabled apache2
  systemd:
    name: apache2
    state: restarted
    enabled: yes
  when: config_auth.changed
