---
# tasks file for roles/ubuntu-Grafana

- name: Install apt-transport-https software-properties-common wget with apt
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget

- name: Add the GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add grafana repository
  copy:
    dest: /etc/apt/sources.list.d/grafana.list
    content: 'deb https://packages.grafana.com/oss/deb stable main'

- name: Install grafana with apt
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Start and Enable grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
