---
# tasks file for roles/ubuntu-Influxdb

- name: Add influxdb repo in /etc/apt/sources.list.d/influxdb.list
  copy:
    dest: /etc/apt/sources.list.d/influxdb.list
    content: deb https://repos.influxdata.com/ubuntu focal stable

- name: Get InfluxData repo using apt-key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Install influxdb using apt
  apt:
    name: influxdb
    state: present
    update_cache: yes

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install influxdb using pip # To enable to execute influxdb_database in ansible
  pip:
    name: influxdb

- name: Start and Enable InfluxDB
  systemd:
    name: influxdb
    state: started
    enabled: yes

- name: Enable http authentication
  copy:
    dest: /etc/influxdb/influxdb.conf
    content: |
      [http]
      auth-enabled = true

# Optional
- mame: Create database
  influxdb_database:
    hostname: "ubuntu-1810839"
    username: "ubuntu-lesliemae"
    password: "leslie15"
    database_name: "ubuntu-influxdb"
    state: present
